spring:
  application:
    name:  digio-backend

digio:
  api:
    base-url: https://rgr3viiqdl8sikgv.public.blob.vercel-storage.com/
    endpoints:
      customer: clientes-Vz1U6aR3GTsjb3W8BRJhcNKmA81pVh.json
      products: produtos-mnboX5IPl6VgG390FECTKqHsD9SkLS.json

customer:
  top:
    percentile: 75
resilience4j:
  circuitbreaker:
    instances:
      customers-circuit-breaker:
        sliding-window-size: 8
        minimum-number-of-calls: 4
      purchases-circuit-breaker:
        sliding-window-size: 8
        minimum-number-of-calls: 4
      products-circuit-breaker:
        sliding-window-size: 8
        minimum-number-of-calls: 4
  retry:
    instances:
      purchases-retry:
        max-attempts: 3
        wait-duration: 500